/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pos.sistemagams.vista;

import java.awt.CardLayout;

/**
 *
 * @author Diego
 */
public class PanelInventario extends javax.swing.JPanel {

    /**
     * Creates new form PanelInventario
     */
    public PanelInventario() {
        initComponents();
        PanelInventarioProductos panelInventarioProductos = new PanelInventarioProductos();
        PanelInventarioMovimientos panelInventarioMovimientos = new PanelInventarioMovimientos();
        PanelInventarioMinimo panelInventarioMinimo = new PanelInventarioMinimo();
        PanelInventarioMaximo panelInventarioMaximo = new PanelInventarioMaximo();
        PanelInventarioEstadisticas panelInventarioEstadisticas = new PanelInventarioEstadisticas();

        panelContenedor.add(panelInventarioProductos, "productos");
        panelContenedor.add(panelInventarioMovimientos, "movimientosinventario");
        panelContenedor.add(panelInventarioMinimo, "inventariominimo");
        panelContenedor.add(panelInventarioMaximo, "inventariomaximo");
        panelContenedor.add(panelInventarioEstadisticas, "estadisticas");
        CardLayout layout = (CardLayout) panelContenedor.getLayout();
        layout.show(panelContenedor, "productos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        btnProductos = new javax.swing.JButton();
        btnInvMovimientos = new javax.swing.JButton();
        btnInvMinimo = new javax.swing.JButton();
        btnInvMaximo = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();

        btnProductos.setText("PRODUCTOS");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        panelSuperior.add(btnProductos);

        btnInvMovimientos.setText("MOVIMIENTOS DE INVENTARIO");
        btnInvMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvMovimientosActionPerformed(evt);
            }
        });
        panelSuperior.add(btnInvMovimientos);

        btnInvMinimo.setText("INV. MINIMO");
        btnInvMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvMinimoActionPerformed(evt);
            }
        });
        panelSuperior.add(btnInvMinimo);

        btnInvMaximo.setText("INV. MAXIMO");
        btnInvMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvMaximoActionPerformed(evt);
            }
        });
        panelSuperior.add(btnInvMaximo);

        btnEstadisticas.setText("ESTADISTICAS");
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        panelSuperior.add(btnEstadisticas);

        panelContenedor.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
            .addComponent(panelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        CardLayout layout = (CardLayout) panelContenedor.getLayout();
        layout.show(panelContenedor, "productos");
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnInvMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvMovimientosActionPerformed
        CardLayout layout = (CardLayout) panelContenedor.getLayout();
        layout.show(panelContenedor, "movimientosinventario");
    }//GEN-LAST:event_btnInvMovimientosActionPerformed

    private void btnInvMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvMinimoActionPerformed
        CardLayout layout = (CardLayout) panelContenedor.getLayout();
        layout.show(panelContenedor, "inventariominimo");
    }//GEN-LAST:event_btnInvMinimoActionPerformed

    private void btnInvMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvMaximoActionPerformed
        CardLayout layout = (CardLayout) panelContenedor.getLayout();
        layout.show(panelContenedor, "inventariomaximo");
    }//GEN-LAST:event_btnInvMaximoActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        CardLayout layout = (CardLayout) panelContenedor.getLayout();
        layout.show(panelContenedor, "estadisticas");
    }//GEN-LAST:event_btnEstadisticasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnInvMaximo;
    private javax.swing.JButton btnInvMinimo;
    private javax.swing.JButton btnInvMovimientos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
}
